CREATE TABLE scout_data (
  id int(11) NOT NULL AUTO_INCREMENT,
  team_number int(255) DEFAULT NULL,
  event_name varchar(256) DEFAULT NULL,
  author varchar(128) DEFAULT NULL,
  create_time datetime DEFAULT NULL,
  move_auto varchar(45) DEFAULT NULL,
  sense_auto varchar(45) DEFAULT NULL,
  over_auto varchar(45) DEFAULT NULL,
  collect_auto varchar(45) DEFAULT NULL,
  place_auto varchar(45) DEFAULT NULL,
  found_auto_d blob,
  sense_auto_d blob,
  park_auto_d blob,
  stone_auto_d blob,
  add_auto_d blob,
  found_teleop varchar(45) DEFAULT NULL,
  collect_teleop varchar(45) DEFAULT NULL,
  palce_teleop varchar(45) DEFAULT NULL,
  found_teleop_d blob,
  stone_teleop_d blob,
  add_teleop_d blob,
  found_end varchar(45) DEFAULT NULL,
  in_end varchar(45) DEFAULT NULL,
  over_end varchar(45) DEFAULT NULL,
  place_end varchar(45) DEFAULT NULL,
  found_end_d blob,
  parki_end_d blob,
  stones_end_d blob,
  add_end_d blob,
  PRIMARY KEY (id)
)